# Generated by Django 4.2.7 on 2025-07-06 03:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('product_viewed', 'Product Viewed'), ('cart_updated', 'Cart Updated'), ('address_added', 'Address Added'), ('address_updated', 'Address Updated'), ('avatar_uploaded', 'Avatar Uploaded'), ('preferences_updated', 'Preferences Updated')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, jpg/jpeg/png/gif only)', null=True, upload_to=store.models.user_avatar_upload_path, validators=[store.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or description', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, help_text='Company name', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for orders and updates'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium account status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title or profession', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_emails',
            field=models.BooleanField(default=False, help_text='Receive marketing and promotional emails'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications for order updates'),
        ),
        migrations.AddField(
            model_name='customer',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media profile links (JSON format)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone preference", max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or business website'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='store_custo_user_id_5b583a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_verified'], name='store_custo_is_veri_0c210a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['account_type'], name='store_custo_account_44efc0_idx'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='store_usera_user_id_b0f3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='store_usera_timesta_1c26b9_idx'),
        ),
    ]
