# Generated by Django 4.2.7 on 2025-07-06 04:47

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_useractivity_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_account_44efc0_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[store.models.validate_us_phone]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(help_text='US postal code (12345 or 12345-6789)', max_length=10, validators=[store.models.validate_us_postal_code]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(help_text='2-letter US state abbreviation', max_length=2, validators=[store.models.validate_us_state]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='store_order_custome_e65576_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='store_order_order_d_1d849c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_archived'], name='store_order_is_arch_4b7986_idx'),
        ),
    ]
