# Generated by Django 4.2.7 on 2025-07-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_customer_store_custo_account_44efc0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('product_viewed', 'Product Viewed'), ('cart_updated', 'Cart Updated'), ('address_added', 'Address Added'), ('address_updated', 'Address Updated'), ('avatar_uploaded', 'Avatar Uploaded'), ('preferences_updated', 'Preferences Updated'), ('system_cleanup', 'System Cleanup')], max_length=20),
        ),
    ]
