# Generated by Django 4.2.7 on 2025-07-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_system_cleanup_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='job_title',
        ),
    ]
