# Generated by Django 4.2.7 on 2025-07-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('signature_verification_failed', 'Signature Verification Failed'), ('invalid_payload', 'Invalid Payload'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('suspicious_activity', 'Suspicious Activity'), ('unauthorized_access', 'Unauthorized Access'), ('malformed_request', 'Malformed Request'), ('duplicate_event', 'Duplicate Event'), ('processing_error', 'Processing Error'), ('success', 'Success')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(default='POST', max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('webhook_source', models.CharField(default='stripe', max_length=50)),
                ('webhook_event_id', models.CharField(blank=True, max_length=255)),
                ('webhook_event_type', models.CharField(blank=True, max_length=50)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('payload_size', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'severity'], name='store_webho_event_t_873200_idx'), models.Index(fields=['ip_address', 'timestamp'], name='store_webho_ip_addr_5b7664_idx'), models.Index(fields=['webhook_source', 'event_type'], name='store_webho_webhook_db1244_idx'), models.Index(fields=['timestamp'], name='store_webho_timesta_2475fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('stripe.checkout.session.completed', 'Stripe Checkout Session Completed'), ('stripe.payment_intent.succeeded', 'Stripe Payment Intent Succeeded'), ('stripe.payment_intent.payment_failed', 'Stripe Payment Intent Failed'), ('stripe.invoice.payment_succeeded', 'Stripe Invoice Payment Succeeded'), ('stripe.customer.created', 'Stripe Customer Created'), ('stripe.customer.updated', 'Stripe Customer Updated'), ('other', 'Other')], max_length=50)),
                ('source', models.CharField(default='stripe', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_size', models.PositiveIntegerField()),
                ('api_version', models.CharField(blank=True, max_length=50)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id', 'status'], name='store_webho_event_i_2805a1_idx'), models.Index(fields=['event_type', 'created_at'], name='store_webho_event_t_5e05dc_idx'), models.Index(fields=['payload_hash'], name='store_webho_payload_68266f_idx'), models.Index(fields=['source', 'status'], name='store_webho_source_a1dca0_idx')],
            },
        ),
    ]
