# Generated by Django 4.2.7 on 2025-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_webhooksecuritylog_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for payment processing', max_length=255, null=True),
        ),
    ]
