# Generated by Django 4.2.7 on 2025-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_add_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, help_text='Shipping carrier (e.g., USPS, UPS)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_estimated_days',
            field=models.IntegerField(blank=True, help_text='Estimated delivery days', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_rate_id',
            field=models.CharField(blank=True, help_text='GoShippo rate ID', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, help_text='Shipping service (e.g., Priority Mail)', max_length=100),
        ),
    ]
